Full mock coverage
lightningrodlabs/hdk_crud pull request #13
Opened 2021-11-02 18:07 UTC by WFinck97

an hdk_crud refactor to be able to mock all the exposed functions for unit testing on the consumer side.

2021-11-02 23:45 UTC, WFinck97 commented
### make remaining hdk_functions mockable
current plan:
1. split remaining functions in `retrieval.rs` into their own file and make them mockable (like [get_latest_for_entry.rs](https://github.com/lightningrodlabs/hdk_crud/blob/main/src/retrieval/get_latest_for_entry.rs))
![image](https://user-images.githubusercontent.com/39413655/139966606-330405ec-3220-4aab-92d9-e076b49516a7.png)

2. make generic crud action functions (in crud.rs) mockable. 
- question: each function will become a struct method such that it can be mocked. Should these structs be defined in crud.rs, or split into their own files like the other mocked functions?

2021-11-02 23:52 UTC, Connoropolous commented
@WFinck97 
I'm thinking... 
along with 'retrieval' which already exists, there could be `chain_actions` mod... 
in it would be a file for `create_action` `update_action` `delete_action`. Separated because these actions affect the source chain

2021-11-03 23:24 UTC, Connoropolous requested changes
I think all my change requests are expressed as mergeable suggestions. 
You can use the bulk 'add suggestion to batch' feature to merge them all at once. 

So close! Excellent

2021-11-03 23:24 UTC, Connoropolous commented on src/chain_actions/fetch_action.rs
> +        let entries = fetch_entries.fetch_entries::<T>( // TODO: change to struct method
```suggestion
        let entries = fetch_entries.fetch_entries::<T>(
```

2021-11-03 23:24 UTC, Connoropolous commented on src/retrieval/utils.rs
> +pub type OptionEntryAndHash<T> = Option<EntryAndHash<T>>;
would prefer these to be in a spot like 'types' or something, but not going to ask that to be done right now.

2021-11-03 23:24 UTC, Connoropolous commented on src/crud.rs
>  /// #[hdk_entry(id = "test")]
```suggestion
/// #[hdk_entry(id = "example")]
```

2021-11-03 23:24 UTC, Connoropolous commented on src/crud.rs
>  /// pub struct Test {
```suggestion
/// pub struct Example {
```

2021-11-03 23:24 UTC, Connoropolous commented on src/chain_actions/create_action.rs
> +}
```suggestion
```

2021-11-03 23:38 UTC, merged